### PR TITLE
add all commands plugin for phpunit

### PR DESCRIPTION
**Pull request by ishikawam**
Hi! Thank you for your this grunt plugin. I'm enjoy it!
and I'd like to merge this commits.
1. bootstrap file path searching logic
2. print command
3. Add available commands

actually, i'd like to use 'configuration' option for my project.
please!

### CODE REVIEW

**Comment by jrcryer** [comment]
+1 for the configuration options - also needed for my project.

@ishikawam possibly create a PR for each option?  The above three commits appear to have a lot going on.

**Comment by SaschaGalley** [comment]
Hi!

Thank you for your effort! I would be more than happy to merge that pull request, but I'm not quite sure about the print command. In my opinion this should be only printed in verbose mode.

It would be awesome if you would follow the suggestion of @jrcryer and create a pull request for each commit.

**Comment by SaschaGalley** [comment]
Merged pull request manually after mergin #3 and ignored print command.

**Comment by ishikawam** [comment]
Thank you, merge my code!!

**Pull request closed without merging**
