### PR TITLE
Moving configuration and options out to dedicated class

### PR DESCRIPTION
**Pull request by jrcryer**

### CODE REVIEW

**Comment by jrcryer** [comment]
Also, should mention that this is the first part of a two part change.  The goal is hopefully to add tests around the plugin.

Cheers

**Comment by SaschaGalley** [comment]
I like the idea of separating the command builder, but I wonder what you have in mind and where you want to go with your second change. I would suggest to move the builder options away from the builder itself. The command builder could be a standalone module. 

However, I also would like this plugin to get testable.

**Comment by jrcryer** [comment]
@SaschaGalley complete agree with your above suggestions.  I am all for the above.

I think the actual running of the task is pretty simple and now the dependencies on their party packages have been reduced, we should be able to test the builder and phpunit class individual.  

If we were to move the builder options outside both of these classes then that would add greater testability.

Cheers

**Comment by jrcryer** [comment]
Hi, 

Long time no speak - any thoughts on merging this so we can start to work on your idea of separating the building out?

Also wondering whether we should pull the test PHP test runner into another repo and make it a submodule of this repo?

Cheers,

James

**Pull request merged**
