### PR TITLE
updated default phpunit to be the one supplied by this task

### PR DESCRIPTION
**Pull request by mitermayer**
I understand that you guys have removed third party dependencies like the composer installation of phpunit. But i think this task would be rather more useful if by default it shipped with a standalone phpunit.phar working version. As long as we state that on the readme like this `This plugin comes with PHPUnit 3.7.19, but other versions can be installed.` this way users can install other versions if they want to, but they will have all they need at start. I hope you guys consider this merge since it is very important for a grunt-init scaffold that our organization is building. 

By the way great job on this task it looks great :)

### CODE REVIEW

**Comment by SaschaGalley** [comment]
I don't really like the idea of shipping third party in a plugin that will be installed with a package manger. Every user will have a different setup, some may have phpunit installed globally. One suggestion for your grunt-init task would be to automatically run the "composer install" shell command (there are some cmd plugins available for grunt).

**Comment by mitermayer** [comment]
@SaschaGalley user would still be able to do that, but shipping with a working version bin is very important.. If composer has to install things you would be adding a third party dependency to composer. By shipping with a default executable you are just giving user an option. What could be done is only include executable of stable versions. So this way doesnt really matter been a bit outdated. Since like you said the user can always have a different setup and install things manually. Think of it as an option, or even recommendation.

**Comment by mitermayer** [comment]
@SaschaGalley This way nothing is installed, the executable comes on as PHAR file on the bin folder.

**Comment by jrcryer** [comment]
@mitermayer I don't think shipping a PHP dependency as part of the Grunt plugin is a good idea.  We give people the ability to configure their own PHP environment.  The aim of this project is to automate running PHPUnit either for development or CI.  I think building PHPUnit with the plugin would add a level of magic that isn't needed.

**Comment by jrcryer** [comment]
:-1:

**Pull request closed without merging**
